Repository Shivansh-007/piston-cli, pull requests merged in 2021-04, with the labels that each got.

#30 Fixes Issues Raised By DeepSource
  piston/colorschemes/dracula.py
  piston/colorschemes/gruvbox.py
  piston/colorschemes/nord.py
  piston/commands/base.py
  piston/commands/from_file.py
  piston/commands/from_input.py
  piston/commands/from_link.py
  piston/commands/from_shell.py
  piston/utilities/maketable.py
  piston/utilities/utils.py
Labels: level: 0 - beginner, priority: 1 - high, status: needs review, type: enhancement

#41 Added missing dependency and missing init file
  piston/configuration/validators/__init__.py
  setup.py
Labels: area: dependencies, level: 0 - beginner, status: needs review

#37 Added ArchOS installation info
  README.md
  packaging/piston/PKGBUILD
Labels: level: 1 - intermediate, priority: 2 - medium, status: needs review

#47 Pipenv to poetry
  .github/workflows/linting.yml
  .github/workflows/python-publish.yml
  Pipfile
  Pipfile.lock
  piston/__init__.py
  piston/__version__.py
  piston/configuration/config_fixer.py
  piston/configuration/validators/box_validator.py
  piston/utils/constants.py
  piston/version.py
  poetry.lock
  pyproject.toml
  setup.py
Labels: area: CI, area: dependencies, level: 1 - intermediate, priority: 1 - high, status: needs review
