Repository Shivansh-007/piston-cli, pull requests merged in 2021-05, with the labels that each got.

#50 Fixing error handling again
  piston/__main__.py
  piston/utils/helpers.py
  piston/utils/services.py
Labels: level: 1 - intermediate, priority: 1 - high, status: approved

#43 Verson 1.4.0
  .flake8
  .github/workflows/linting.yml
  .github/workflows/python-publish.yml
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  README.md
  config.yaml
  media/branding/piston_v1_logo_dist.png
  media/branding/piston_v1_logo_src.svg
  media/branding/piston_v2_logo_dist.png
  media/branding/piston_v2_logo_src.svg
  packaging/arch/PKGBUILD
  piston/__init__.py
  piston/__main__.py
  piston/colorschemes/__init__.py
  piston/colorschemes/dracula.py
  piston/colorschemes/gruvbox.py
  piston/colorschemes/nord.py
  piston/commands/__init__.py
  piston/commands/base.py
  piston/commands/from_file.py
  piston/commands/from_input.py
  piston/commands/from_link.py
  piston/commands/from_shell.py
  piston/commands/theme_list.py
  piston/configuration/choose_config.py
  piston/configuration/config_fixer.py
  piston/configuration/config_loader.py
  piston/configuration/validators/box_validator.py
  piston/configuration/validators/theme_validator.py
  piston/configuration/validators/validator_base.py
  piston/utilities/maketable.py
  piston/utilities/utils.py
  piston/utils/__init__.py
  piston/utils/compilers.py
  piston/utils/constants.py
  piston/utils/helpers.py
  piston/utils/lang_extensions.py
  piston/utils/lexers.py
  piston/utils/maketable.py
  piston/utils/prompt_continuation.py
  piston/utils/services.py
  piston/utils/theme_preview.py
  piston/version.py
  poetry.lock
  pyproject.toml
  setup.py
Labels: area: CI, area: dependencies, level: 1 - intermediate, priority: 1 - high, status: needs review

#56 Feature: Make prompt in shell mode configurable
  piston/__init__.py
  piston/commands/from_shell.py
  piston/configuration/config_fixer.py
  piston/configuration/validators/prompt_validator.py
  piston/utils/constants.py
  piston/utils/prompt_continuation.py
Labels: level: 0 - beginner, priority: 2 - medium, status: needs review

#64 Initial Nix Support
  .envrc
  .gitignore
  README.md
  flake.lock
  flake.nix
  packaging/nix/default.nix
  packaging/nix/shell.nix
Labels: area: OS support, level: 1 - intermediate, status: needs review

#65 Implement signal handling (Currently only SIGINT) - Solves #62
  piston/__main__.py
  piston/utils/helpers.py
Labels: level: 1 - intermediate, priority: 1 - high, status: WIP
