Repository Shivansh-007/piston-cli, pull requests merged in 2021-02, with the labels that each got.

#6 Bug Report and Feature Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: level: 0 - beginner, priority: 2 - medium, status: needs review

#11 Ignore vscode configuration
  .gitignore
Labels: level: 0 - beginner, status: approved

#9 Implemented shell flag
  piston/__init__.py
  piston/commands/__init__.py
  piston/commands/base.py
  piston/commands/from_file.py
  piston/commands/from_input.py
  piston/commands/from_link.py
  piston/commands/from_shell.py
  piston/utilities/constants.py
  piston/utilities/prompt_continuation.py
Labels: level: 1 - intermediate, priority: 2 - medium, status: needs review, type: feature

#14 Hot Fix On Sys Arguments and Inputs
  piston/commands/from_file.py
  piston/commands/from_input.py
  piston/commands/from_link.py
  piston/commands/from_shell.py
Labels: level: 0 - beginner, priority: 2 - medium, status: needs review, type: bug

#17 Add NixOS installation instructions
  README.md
Labels: documentation, priority: 3 - low, status: planning

#23 Add Pull Request Template
  .github/pull_request_template.md
Labels: documentation, status: needs review
